website/config/routes.rb
Vitalpatch::Application.routes.draw do

  mount RailsAdmin::Engine => '/cms', :as => 'rails_admin'
  devise_for :admins

  root 'home#index'
  post '/create' => 'home#create'
  get '/unsub' => 'home#unsub'

end

website/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  # No registration in production
  if Rails.env.production?
    devise :database_authenticatable, :recoverable,
           :rememberable, :trackable, :validatable
  else
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
  end
end

website/app/models/user.rb
class User < ActiveRecord::Base
  validates :email, email: true, uniqueness: true
end

website/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

website/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # Email
      UserMailer.send_mailchimp(@user)
      flash[:notice] = "Successfully added"
      redirect_to root_path
    else
      flash[:error] = "Could not add: %s" % @user.errors.full_messages
      redirect_to root_path
    end
  end

  def unsub
    email = URI.unescape(params[:md_email])
    user = User.where(email: email)
    puts email
    if user && user.destroy_all
      @message = "Your email " + email + " was successfully unsubscribed."
    else
      @message = "Sorry, there was an error: %s" % user.errors.full_messages
    end
  end

  private
  def user_params
    params.permit(:email)
  end
end

website/app/helpers/application_helper.rb
module ApplicationHelper
end

website/app/helpers/home_helper.rb
module HomeHelper
end

website/app/views/home/create.html.erb
<h1>Home#create</h1>
<p>Find me in app/views/home/create.html.erb</p>

website/app/views/home/index.html.erb
<% content_for :head do %>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/favicon.png">

    <title>Vital Patch</title>

    <!-- Bootstrap core CSS -->
    <link href="assets/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="assets/main.css" rel="stylesheet">

    <!-- Fonts from Google Fonts -->
	<link href='http://fonts.googleapis.com/css?family=Lato:300,400,900' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-47108109-1', 'vitalpatch.herokuapp.com');
	  ga('send', 'pageview');
	</script>

<% end %>


<section id="top">
<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#top"><b>Vital Patch</b></a>
    </div>
    <div class="navbar-collapse collapse">
	  <ul class="nav navbar-nav navbar-left">
	  	<li><a href="#about">About</a></li>
        <li><a href="#problem">Problem</a></li>
        <li><a href="#solution">Solution</a></li>
        <li><a href="#team">Team</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
        <form class="form-inline" role="form" method="post" action=<%= create_path %>>
			  <div class="form-group">
			    <input type="email" name="email" class="form-control form-control-sm" id="exampleInputEmail1" placeholder="Enter your email address">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
			  </div>
			  <button type="submit" class="btn btn-warning btn-sm">Invite Me!</button>
			</form>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
</section>

<% if flash[:notice] %>
	<div class="alert alert-success alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<center><strong><%= flash[:notice] =%></strong></center>
	</div>
<% end %>

<% if flash[:error] %>
	<div class="alert alert-danger alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<center><strong><%= flash[:error] =%></strong></center>
	</div>
<% end %>

<div id="headerwrap">
	<div class="container">
		<div class="row">
			<div class="col-lg-7">
				<h1>Independence seniors deserve, <br/>
				peace of mind for their families.</h1>
				<form class="form-inline" role="form" method="post" action=<%= create_path %>>
				  <div class="form-group">
				    <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="Enter your email address">
				    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
				  </div>
				  <button type="submit" class="btn btn-warning btn-lg">Invite Me!</button>
				</form>
			</div><!-- /col-lg-6 -->
			<div class="col-lg-5">
				<img class="img-responsive" src="assets/old_imgs/ipad-hand.png" alt="">
			</div><!-- /col-lg-6 -->

		</div><!-- /row -->
	</div><!-- /container -->
</div><!-- /headerwrap -->

<section id="about">
	<div class="container">
		<div class="row mt centered">
			<div class="col-lg-6 col-lg-offset-3">
				<h1>About</h1>
				<h3>Let's get down to brass tacks.</h3>
			</div>
		</div><!-- /row -->

		<div class="row mt centered">
			<div class="col-lg-6">
				<img src="assets/icon_10412/icon_10412_modified.png" width="180" alt="">
			</div><!--/col-lg-3 -->

			<div class="col-lg-6">
				<h4>The Crux</h4>
				<p><b>Vital Patch</b> is a revolutionary fall-detection device for seniors. It's easy to wear, unobtrusive, and gives seniors the independence they deserve while offering peace of mind to their families. It consists of a pulse monitor, thermometer, accelerometer, gyroscope, and wifi transceiver all packed in a comfortable bandage that is easily removable from the skin.</p>
			</div><!--/col-lg-3 -->
		</div><!-- /row -->

		<div class="row mt centered">
			<div class="col-lg-6">
				<h4>Falling Alerts</h4>
				<p>Using a state of the art algorithm, <b>Vital Patch</b> is able to detect when falls occur.  It will then send out an alert to let the proper people know that help is needed.  And the great part is, you can decide who to alert; some common examples are your loved ones, a caretaker, or 911.</p>
			</div><!--/col-lg-3 -->
			<div class="col-lg-6">
				<img src="assets/icon_18418/icon_18418_modified.png" width="180" alt="">
			</div><!--/col-lg-3 -->
		</div><!-- /row -->

		<div class="row mt centered">
			<div class="col-lg-6">
				<img src="assets/icon_144/icon_144_modified.png" width="180" alt="">
			</div><!--/col-lg-3 -->

			<div class="col-lg-6">
				<h4>Peace of Mind</h4>
				<p><b>Vital Patch</b> keeps track of your pulse and temperature vitals, allowing you and your loved ones to be able to check in with how you're doing.  Now, you can see how healthy you are, and how your health has changed over time.  Peace of mind for you, peace of mind for your family.</p>
			</div><!--/col-lg-3 -->
		</div><!-- /row -->
	</div><!-- /container -->
</section>

<hr>

<section id="problem">
	<div class="container">
		<div class="row mt centered">
			<div class="col-lg-6 col-lg-offset-3">
				<h1>Problem</h1>
				<h3>Why is this such a big deal?</h3>
			</div>
		</div><!-- /row -->

		<div class="row mt centered">
			<div class="col-lg-6">
				<img src="assets/icon_15484/icon_15484.png" width="180" alt="">
			</div><!--/col-lg-3 -->

			<div class="col-lg-6">
				<h4>Number One Cause of Injury Deaths</h4>
				<p>In seniors, falls are the number one cause of fractures, hospital admissions for trauma, loss of independence, and injury deaths.</p>
			</div><!--/col-lg-3 -->
		</div><!-- /row -->

		<div class="row mt centered">
			<div class="col-lg-6">
				<h4>Signs of Other Medical Issues</h4>
				<p>Falls can be a sign of a new medical problem that needs attention, such as diabetes or changes in blood pressure. Falls can also be a sign of problems with medications or eyesight that can be easily corrected once detected.</p>
			</div><!--/col-lg-3 -->

			<div class="col-lg-6">
				<img src="assets/icon_2384/icon_2384.png" width="180" alt="">
			</div><!--/col-lg-3 -->
		</div><!-- /row -->
	</div><!-- /container -->
</section>

<hr>

<section id="solution">
	<div class="container">
		<div class="row mt centered">
			<div class="col-lg-6 col-lg-offset-3">
				<h1>Solution</h1>
				<h3>What makes Vital Patch the bees' knees.</h3>
			</div>
		</div><!-- /row -->

		<div class="row mt centered">
			<div class="col-lg-3">
				<img src="assets/icon_8194/icon_8194_modified.png" width="180" alt="">
				<h4>1 - Customizable Alerts</h4>
				<p>Automatically place a call to your designated caretaker and/or family member when a fall is detected.</p>
			</div><!--/col-lg-3 -->

			<div class="col-lg-3">
				<img src="assets/icon_186/icon_186_modified.png" width="180" alt="">
				<h4>2 - Battery Life</h4>
				<p>Three days of continuous monitoring on a single charge.  Vital Patch comes with two free recharable batteries!</p>
			</div><!--/col-lg-3 -->

			<div class="col-lg-3">
				<img src="assets/icon_25120/icon_25120_modified.png" width="180" alt="">
				<h4>3 - Sleek Design</h4>
				<p>Compact design allows Vital Patch to be secured with a simple adhesive bandage.</p>
			</div><!--/col-lg-3 -->

			<div class="col-lg-3">
				<img src="assets/icon_2759/icon_2759_modified.png" width="180" alt="">
				<h4>4 - Historical Data</h4>
				<p>Track your Vital Patch history and manage who has access through privacy settings.</p>
			</div><!--/col-lg-3 -->
		</div><!-- /row -->
	</div><!-- /container -->
</section>

<hr>

<section id="team">
	<div class="container">
		<div class="row mt centered">
			<div class="col-lg-6 col-lg-offset-3">
				<h1>Our Awesome Team</h1>
				<h3>The brains, brawn, and brains behind Vital Patch.</h3>
			</div>
		</div><!-- /row -->

		<div class="row mt centered">
			<div class="col-lg-4">
				<img class="img-circle" src="assets/team/fareeha.jpg" width="140" alt="">
				<h4>Fareeha Ali</h4>
				<p>Fareeha is a reporting extraordinaire. She founded the New York Times, the Wall Street Journal, and NASA.  When she was 20.</p>
				<p>
					<a href="mailto:samtoizer@gmail.com"><i class="glyphicon glyphicon-envelope"></i></a>
				</p>
			</div><!--/col-lg-4 -->

			<div class="col-lg-4">
				<img class="img-circle" src="assets/team/ed.jpg" width="140" alt="">
				<h4>Ed Brennink-Meyer</h4>
				<p>Try asking Ed about his finances. He'll blow you away. Talk about someone who's on top of their game.</p>
				<p>
					<a href="mailto:samtoizer@gmail.com"><i class="glyphicon glyphicon-envelope"></i></a>
				</p>
			</div><!--/col-lg-4 -->

			<div class="col-lg-4">
				<img class="img-circle" src="assets/team/michael.jpg" width="140" alt="">
				<h4>Michael Hueschen</h4>
				<p>Michael is a senior at Northwestern. His interests include functional programming, body weight workouts, and living primally.</p>
				<p>
					<a href="mailto:michaelhueschen@gmail.com"><i class="glyphicon glyphicon-envelope"></i></a>
				</p>
			</div><!--/col-lg-4 -->
		</div><!-- /row -->

		<div class="row mt centered">
			<div class="col-lg-4">
				<img class="img-circle" src="assets/team/scott.jpg" width="140" alt="">
				<h4>Scott Neaves</h4>
				<p>Northwestern University student in computer science, class of 2014. Interests include web development, live music, and drawing.</p>
				<p>
					<a href="mailto:scottneaves2014@u.northwestern.edu"><i class="glyphicon glyphicon-envelope"></i></a>
				</p>
			</div><!--/col-lg-4 -->

			<div class="col-lg-4">
				<img class="img-circle" src="assets/team/ryan.jpg" width="140" alt="">
				<h4>Ryan Rennaker</h4>
				<p>Ryan is a second year Kellogg MBA candidate focusing in Finance and Marketing. Prior to Kellogg, Ryan worked at Google in San Francisco. His interests include entrepreneurship and rugby.</p>
				<p>
					<a href="mailto:rrennaker2014@kellogg.northwestern.edu"><i class="glyphicon glyphicon-envelope"></i></a>
				</p>
			</div><!--/col-lg-4 -->

			<div class="col-lg-4">
				<img class="img-circle" src="assets/team/sam.jpg" width="140" alt="">
				<h4>Sam Toizer</h4>
				<p>Sam is an undergraduate computer science student at Northwestern University, class of 2014, with a strong passion for UI/UX design. In his free time he enjoys playing/writing music, and reading.</p>
				<p>
					<a href="mailto:samtoizer@gmail.com"><i class="glyphicon glyphicon-envelope"></i></a>
				</p>
			</div><!--/col-lg-4 -->
		</div><!-- /row -->
	</div><!-- /container -->
</section>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="assets/bootstrap.min.js"></script>
<script src="assets/smoothScroll.js"></script>

website/app/views/home/unsub.html.erb
<% content_for :head do %>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/favicon.png">

    <title>Vital Patch</title>

    <!-- Bootstrap core CSS -->
    <link href="assets/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="assets/main.css" rel="stylesheet">

    <!-- Fonts from Google Fonts -->
	<link href='http://fonts.googleapis.com/css?family=Lato:300,400,900' rel='stylesheet' type='text/css'>
    
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
	
<% end %>


<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><b>Vital Patch</b></a>
    </div>
    <div class="navbar-collapse collapse">	  
      <ul class="nav navbar-nav navbar-right">
        <li>
        <form class="form-inline" role="form" method="post" action=<%= create_path %>>
			  <div class="form-group"> 
			    <input type="email" name="email" class="form-control form-control-sm" id="exampleInputEmail1" placeholder="Enter your email address">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
			  </div>
			  <button type="submit" class="btn btn-warning btn-sm">Invite Me!</button>
			</form>					
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<h2 class="unsubscribe-message"><%= @message %></h2>

website/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vitalpatch</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>

<%= yield %>

</body>
</html>